apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- digest: outlook.com/nodejs-argocd
  name: nodejs-argocd
  newName: vpanian
