apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-argocd
  namespace: argocd
spec:
  destination:
    namespace: nodejs
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/VladPanian/argocd-circle"
    targetRevision: circleci-project-setup
  project: default
